Feature/auth with API KEY
Cocolis-1/cocolis-php pull request #32
Opened 2022-01-14 02:01 UTC by btnalexandre

2022-01-14 02:01 UTC, btnalexandre commented
Code coverage 100%

2022-01-17 13:04 UTC, sebfie requested changes

2022-01-17 13:04 UTC, sebfie commented on src/Client.php
>      }
else if (empty($auth['api_key'])) Exception

Si j'ai pas mis la api_key, ca doit raise une erreur

2022-01-17 13:04 UTC, sebfie commented on tests/ClientTest.php
> +    $this->expectExceptionMessage('Key app_id is missing');
C'est une api_key et tu envois l'erreur 'Key app_id is missing' :) Il faut mieux faire la validation dans le constructeur

2022-01-21 16:39 UTC, btnalexandre commented on src/Client.php
>      }
Done :)

2022-01-24 20:34 UTC, sebfie commented
Il me semble qu'il manque l'essentiel, la mise à jour de la documentation :p 

Ici tu fais un tab Recommandé (API KEY) et Déprécié (Tokens)

<img width="683" alt="CleanShot 2022-01-24 at 21 33 32@2x" src="https://user-images.githubusercontent.com/862129/150860257-3303a618-6882-422c-b93e-14cec0c6e4c1.png">

Tu rajoutes aussi une catégorie : Comment obtenir son API KEY avec des captures d'écran... tout beau.

2022-01-24 20:34 UTC, sebfie requested changes
La doc

2022-01-24 20:34 UTC, sebfie commented on src/Version.php
> +    return $json->version;
+1

2022-01-24 20:34 UTC, sebfie commented on src/Version.php
> +    return $json->version;
Super !

2022-01-26 11:42 UTC, btnalexandre commented on src/Version.php
> +    return $json->version;
:)

2022-01-26 13:18 UTC, btnalexandre commented
> Tu rajoutes aussi une catégorie : Comment obtenir son API KEY avec des captures d'écran... tout beau.

Pour ça vaut-il mieux pas update la doc api ?

2022-01-26 13:56 UTC, sebfie commented
Je prendrai peut etre ta doc et ja la copierai dans la doc api :p Mais il la faut un peu partout c'est trop important !

2022-01-28 00:42 UTC, btnalexandre commented
on est good?

2022-01-28 09:52 UTC, sebfie commented
![CleanShot 2022-01-28 at 10 52 02](https://user-images.githubusercontent.com/862129/151525539-5aed2ecc-dcf2-491d-a761-9c2bd8b2b0d1.png)

Je veux en rouge un message, genre : Update janvier 2022. Changement de la méthode d'authentification, à partir de maintenant nous recommandons l'authentification par clée api.

2022-01-28 12:49 UTC, btnalexandre commented
bien vu

2022-02-07 12:58 UTC, btnalexandre commented
@sebfie c'est ok pour toi?

2022-06-21 13:12 UTC, sebfie requested changes
J'avais oublié d'envoyer ma review...

2023-05-15 09:56 UTC, merged